### ISSUE TITLE
no return statement in function returning non-void

### ISSUE THREAD

**Issue by JackMcCoy** [Mohammad-Abdul-Hadi/Adaptive-Online-Biterm-Topic-Modeling#1]
I'm trying out the code, and don't get past loading the docs for the first day. When I add in a cout statement to try to debug (maybe generating the biterms takes a long time), I receive the following error:

```
g++  -c -pipe -O3 obtm.cpp -o obtm.o
In file included from doc.h:9,
                 from obtm.cpp:7:
biterm.h: In member function ‘int Biterm::set_z(int)’:
biterm.h:32:27: warning: no return statement in function returning non-void [-Wreturn-type]
   32 |   int set_z(int k) {z = k;}
      |                           ^
g++ obtm.o ibtm.o main.o -o run
```

**Comment by Mohammad-Abdul-Hadi** [comment]
I am sorry about that.
Must have messed up before a quick push.
I have changed the return type to void.
Thanks!
